Updated Dependencies
braintree/event-emitter pull request #18
Opened 2023-08-22 21:40 UTC by ibooker

Updated:

- Update node to v18
- Update to latest version of TypeScript
- Update to latest version of prettier & eslint-plugin-prettier, ran prettier
- Minor updates for other dependencies

For internal tracking -> 2919

2023-08-24 16:26 UTC, oscarleonnogales approved these changes

2023-08-24 16:28 UTC, oscarleonnogales requested changes
Missing the change on here: https://github.com/braintree/event-emitter/blob/main/.github/workflows/ci.yml#L15

2023-08-28 17:51 UTC, jplukarski requested changes

2023-08-28 17:51 UTC, jplukarski commented on CHANGELOG.md
> + - Dependency Updates
We decided to split these by "Dependency" and "DevDependency" in our other PRs. These would all be "DevDependency" updates and then `Node to v18` should be in the "Dependency Updates" section

2023-08-30 21:28 UTC, jplukarski approved these changes

2023-09-06 16:20 UTC, oscarleonnogales approved these changes

2023-09-06 16:24 UTC, merged

2024-05-07 18:55 UTC, deatonsandra21 approved these changes

2024-05-07 18:56 UTC, deatonsandra21 approved these changes